name: Go CI

on:
    push:
      paths:
        - '2024/**'           
        - '.github/workflows/**'

jobs:
  go-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: |
          cd 2024
          go mod tidy

      - name: Run tests
        run: |
          cd 2024
          go test ./...

      - name: Build and run Go files (excluding *_test.go)
        run: |
            cd 2024
            for dir in */ ; do
                cd "$dir"
                for file in *.go; do
                # Skip *_test.go files
                if [[ "$file" != *_test.go ]]; then
                    go run "$file"
                fi
                done
                cd ..
            done